version: '3'
services:
  go:
    command: ./scripts/go-build.sh
    build:
      context: ./
      dockerfile: ./Dockerfile_go
    volumes:
      - .:/go/src/nomof
    depends_on:
      - dynamodb
    environment:
      - DYNAMO_ENDPOINT=http://dynamodb:8000/
    networks:
      - net

  dynamodb:
    build:
      context: ./
      dockerfile: ./Dockerfile_dynamodb
    ports:
      - '8000:8000'
    networks:
      - net

networks:
  net:
    driver: bridge

