FROM golang:1.10.2-alpine

RUN apk add --no-cache git bash make && \
    go get -u github.com/golang/dep/cmd/dep && \
    go get -u github.com/golang/lint/golint

WORKDIR /go/src/nomof
COPY . /go/src/nomof

RUN ./scripts/go-build.sh

